"use client";

import Link from "next/link";
import { useState } from "react";
import { useAuth } from "@/components/AuthProvider";

export default function RegisterPage() {
  const { register } = useAuth();
  const [form, setForm] = useState({ display_name:"", email:"", password:"", handedness:"right" as "right"|"left" });
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await register(form);}catch(err){setError(err instanceof Error?err.message:"Unable to create account");setBusy(false)}}
  return <main className="auth-page"><div className="auth-visual register"><img src="/logo.jpg" alt="StrikePath AI"/><div className="auth-visual-copy"><span>START YOUR DATASET</span><h2>Your best lane read starts with your own history.</h2><p>StrikePath personalizes recommendations around your hand, equipment, execution, and actual outcomes.</p></div></div><div className="auth-panel"><Link href="/" className="marketing-brand auth-brand"><span className="brand-orbit small"><span className="brand-ball" /></span><strong>STRIKEPATH</strong><em>AI</em></Link><form onSubmit={submit} className="auth-form"><div><small>Create your account</small><h1>Build your bowling profile</h1><p>You can add equipment and start a session immediately.</p></div>{error&&<div className="error-banner">{error}</div>}<label className="field"><span>Display name</span><input required minLength={2} value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} placeholder="Frederick"/></label><label className="field"><span>Email</span><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label className="field"><span>Password</span><input type="password" required minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 8 characters"/></label><div className="handedness-select"><span>Bowling hand</span><div><button type="button" className={form.handedness==="right"?"active":""} onClick={()=>setForm({...form,handedness:"right"})}>Right-handed</button><button type="button" className={form.handedness==="left"?"active":""} onClick={()=>setForm({...form,handedness:"left"})}>Left-handed</button></div></div><button className="primary-button wide" disabled={busy}>{busy?"Creating account…":"Create account"}</button><p className="terms-copy">By continuing, you agree to the product terms and privacy policy your company publishes before commercial launch.</p><p className="auth-switch">Already have an account? <Link href="/login">Sign in</Link></p></form></div></main>;
}
